### ISSUE TITLE
Add livenessProbe to Parity StatefulSet

### ISSUE THREAD

**Issue by medvedev1088** [blockchain-etl/blockchain-kubernetes#2]
Subtasks:

1. Add additional container here https://github.com/blockchain-etl/blockchain-kubernetes/blob/dev/eth-prod-statefulset.yaml, called `query-last-synced-block`. This container's job is to periodically query latest block number from the `parity` container via JSON RPC and write it to the data volume to `/data/blockchain-etl/last_synced_block.txt`. It must overwrite the file only if the new content is different from the current content.
    - `watch` command can be used. Example here https://github.com/blockchain-etl/blockchain-etl-streaming/blob/master/base/deployment.yaml#L79

2. Add liveness probe to `parity` container that checks latest updated date of the `last_synced_block.txt` file. An example is below:

```
livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "file=/data/blockchain-etl/last_synced_block.txt;
            if [ ! -f $file ]; then echo \"File $file does not exist\" && exit 1; fi;
            file_age=$(($(date +%s) - $(date -r $file +%s)));
            max_age=${LAST_SYNCED_BLOCK_FILE_MAX_AGE_IN_SECONDS};
            echo \"$file age is $file_age seconds. Max healthy age is $max_age seconds\";
            if [ $file_age -lt $max_age ]; then exit 0; else exit 1; fi"
          initialDelaySeconds: 300
          periodSeconds: 300
          timeoutSeconds: 5
          failureThreshold: 1
```
3. Test.

Alternative solution: bundle everything into the liveness probe without additional container (i.e. the liveness probe will query the JSON RPC, parse it, save block number to file and check last updated date). More efficient usage of resources but concerns are not separated.

Additional info:

- https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-command
- https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
- https://www.stratoscale.com/blog/kubernetes/auto-healing-containers-kubernetes/

**Comment by allenday** [comment]
@medvedev1088 @voron is this issue still valid?

**Comment by medvedev1088** [comment]
@allenday I can see our livenessProbe is used in the stateful set https://github.com/blockchain-etl/blockchain-kubernetes/blob/dev/charts/parity/templates/statefulset.yaml#L61
